
There are two kinds of Makefiles: One for use with other software of the
husky project (Makefile) and one for standalone-compiling of MsgEd TE
(makefile.*).

To use the Husky-Makefile, you have to create a Makefile-Config (huskymak.cfg)
in the directory above the MsgEd sources.
A sample and some notes on the new Makefile (README.Makefiles) are included
in the husky-common package which can be found on
"http://husky.physcip.uni-stuttgart.de/".

- sms, Sascha.Silbe@ldknet.org, 2:2435/424

